[package]
name = "vibe-vk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Vulkan backend for vibeEngine"

[dependencies]
ash.workspace = true
log.workspace = true
thiserror.workspace = true
vibe-rhi.workspace = true
vibe-graph.workspace = true

[lints.rust]
unsafe_code = "allow"
